### ISSUE TITLE
Discuss: Folder structure

### ISSUE THREAD

**Issue by dreafusion** [quicksolutions/starter-kit#6]
Up for discussion is the usage of a src folder. 

Also up for discussion is the usage of dividing the src folder up immediately with a client folder for front end for the inevitable project that is full stack in one repo.

**Comment by davidragsdale** [comment]
These are not all the arguments that exist, but this is what I could think of at the moment.

Arguments for a `/src` folder:
1. Clearly differentiates between source code and built/distribution code.
2. Separates code from configuration files which typically live in the root of a repo.
3. Is a convention that many developers recognize.

Arguments against:
1. Moves further away from the way files appear on a server.
2. If web output is handled dynamically, why does it matter where the disparate parts of a website live? This is a concept borrowed from the compiled language community where all code must be in a single directory so that it can be compiled. That is not how the web works.
3. It is common to see a "single entry point" as existing inside a `/src` folder. This is more true for front end frameworks than it is for websites without a front end framework.
4. If too many configuration files are the problem, why solve it by sequestering the code?
5. Source code is not the only thing people are editing. It's not necessarily logical that styles, images, or static files should be considered "source code". Why not separate these types of files in directories such as `/styles`, `/scss`, `/assets`, `/static`, `/images`, or `/downloads`?
6. Frameworks such as Nuxt or Next borrow the above separation by creating directories like `/pages` for dynamic pages and `/components` for components that will be created. This is logical because the point of entry for these frameworks is actually a config file and command-line flags.

**Comment by dreafusion** [comment]
Responses: 

In my opinion, all of the arguments against are extremely weak.  Some of them are not even arguing the concept of separating code that will become the actual website, but just a matter of how to call it and what exact structure to use. 

1. It doesn't matter how they appear on the server when you are organizing files for a human developer. 
2. Again, We want to organize for a human developer.  By using directories we can organize files so they are easy to find.

Point 5 is the only one worth responding to, and we still have that distinction within src. 

I vote for using src and putting client side code in the client folder, so you could also have a server folder and a shared folder if you needed it.  I think most people are familiar with this convention.  Most developers will immediately see all the config files and know those are not the files they need to edit and they can make changes in the src folder.

**Comment by davidragsdale** [comment]
I would disagree on dismissing the arguments. While we shouldn't be optimizing for the server, we should be optimizing for our developers, many of which are much more familiar with standard server file structure than they are with larger application file structures. I do feel like a `/src` directory is an unnecessary directory, especially when it only contains directories. Don't bury files for no reason.

**Comment by dreafusion** [comment]
Yeah I think after talking to you about it, it made more sense.  I'm fine with anything as long as there is structure and its easy for others to follow.  Bonus points if it aligns with what we will be doing in future phases.

**Comment by davidragsdale** [comment]
Concensus gained in meeting on 12/2/19. In lieu of using a fully-fledged front end framework (carrying its own opinions of folder structure), follow the practice of using the following folders:
- `/assets` - locations of JS and SCSS entry points.
- `/components` - .hbs partials to be included in pages.
- `/pages` - .hbs page content that includes partials as needed.
- `/public` - Auto-generated. Output files of HTML, JS, and CSS.

This does not include a `/layouts` directory that would contain a wrapper of page content, but one could exist if that functionality was supported by the Handlebars prerendering tool.

**Comment by davidragsdale** [comment]
Adding a `/layouts` directory would add overhead to the prerendering tool of registering a scope containing the current page/path in addition to injecting the page partial at the proper placeholder (similar to `<nuxt />` in Nuxt layouts).
